# Generated by Django 2.0.7 on 2018-07-31 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('click_ip', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('request_log', models.TextField(blank=True, null=True)),
                ('request_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Click')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('cron_url', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_offer', models.SmallIntegerField(default=1)),
                ('virtual_click', models.SmallIntegerField(default=0)),
                ('virtual_lead', models.SmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Domain')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('redirect_link', models.CharField(max_length=255)),
                ('click_rate', models.FloatField(default=0.0)),
                ('geo_locations', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('allow_devices', models.SmallIntegerField(default=0)),
                ('net_offer_id', models.BigIntegerField(default=0)),
                ('allow_multi_lead', models.BooleanField(default=False)),
                ('check_click_in_network', models.BooleanField(default=False)),
                ('number_when_click', models.SmallIntegerField(default=0)),
                ('number_when_lead', models.SmallIntegerField(default=0)),
                ('reject', models.BooleanField(default=False)),
                ('auto', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Network')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='click',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Offer'),
        ),
        migrations.AddField(
            model_name='click',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
