# Generated by Django 2.0.7 on 2018-07-31 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-created_at']},
        ),
    ]
