# Generated by Django 2.0.7 on 2018-07-31 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180731_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='user',
        ),
        migrations.RemoveField(
            model_name='click',
            name='user',
        ),
        migrations.RemoveField(
            model_name='network',
            name='domain',
        ),
        migrations.AddField(
            model_name='network',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
