# Generated by Django 2.0.7 on 2018-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180731_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='allow_devices',
            field=models.SmallIntegerField(choices=[(1, 'All'), (2, 'Mobile'), (3, 'Desktop'), (4, 'Only Android Mobiles (Phone && Tablet)'), (5, 'Only iOS Mobiles (Phone && Tablet)'), (6, 'Only Iphone'), (7, 'Only Ipad')], default=1),
        ),
    ]
