# Generated by Django 2.0.7 on 2018-08-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtual',
            name='process',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
