# Generated by Django 2.0.7 on 2018-08-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_virtual_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual',
            name='sent',
            field=models.NullBooleanField(),
        ),
    ]
