# Generated by Django 2.0.7 on 2018-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180802_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtual',
            name='agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
