# Generated by Django 2.0.7 on 2018-08-03 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_virtual_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='virtual',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='network',
            name='user',
        ),
        migrations.AddField(
            model_name='network',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
