# Generated by Django 2.0.7 on 2018-08-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_click_who_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_id', models.IntegerField(blank=True, null=True)),
                ('lead_json', models.TextField(blank=True, null=True)),
                ('lead_time', models.DateTimeField(blank=True, null=True)),
                ('click_id', models.IntegerField(blank=True, null=True)),
                ('click_user_id', models.IntegerField(blank=True, null=True)),
                ('click_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('click_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('click_time', models.DateTimeField(blank=True, null=True)),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('offer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_net_id', models.BigIntegerField(blank=True, null=True)),
                ('offer_click_rate', models.FloatField(blank=True, null=True)),
                ('offer_network_id', models.IntegerField(blank=True, null=True)),
                ('offer_network_name', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_device', models.SmallIntegerField(blank=True, null=True)),
                ('offer_geos', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_redirect_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='last_cron_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together={('lead_id', 'click_id')},
        ),
    ]
