# Generated by Django 2.0.7 on 2018-08-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180809_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-updated_at',)},
        ),
    ]
