# Generated by Django 2.0.7 on 2018-08-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_statistic_is_sound_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='allow_devices',
            field=models.SmallIntegerField(choices=[(1, 'All'), (2, 'Mobile'), (3, 'Desktop'), (4, 'Only Android Mobiles (Phone && Tablet)'), (5, 'Only iOS Mobiles (Phone && Tablet)')], default=1),
        ),
    ]
